### ISSUE TITLE
Rails group project kanban Board

### ISSUE THREAD

**Issue by VICTOR-CHUKWU** [VICTOR-CHUKWU/rails-recipe-app#6]
- [x] link to project:  [https://github.com/VICTOR-CHUKWU/rails-recipe-app](https://github.com/VICTOR-CHUKWU/rails-recipe-app)
- [x] team of 3 members
- [x] member 1: @tufoinnkuo10 
- [x] member 2: @Whoistolu 
- [x] member 3: @VICTOR-CHUKWU

**Comment by uwadonat** [comment]
Hi **@Team**, :hand: 

Good job so far! :mechanical_arm:
There are some issues that you still need to work on to go to the next project but you are almost there!


## Status: Required Changes ♻️

- [ ] One column (**In Review** )is missing from your board. kindly add it and ask for another review

here is your current board:
![Screenshot from 2022-02-07 15-12-47](https://user-images.githubusercontent.com/65860678/152795153-fd25de0f-6864-4200-8966-1f5f9e1287d8.png)



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Comment by SajjadAhmad14** [comment]
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:

### Hi team, 
## Congratulations 🎉 Thank you for implementing all the requirements 🙏
### Please go ahead and merge the branch!

## Happy Coding 👏👏👏
#### Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by Whoistolu** [comment]
@SajjadAhmad14 Thank you for your feedback 👍🏽
